Unfortunately this update breaks things
    error: while evaluating the attribute 'mods.rs.cardano_0_1_0' at /home/clacke/git/fractalide/fractalide/modules/default.nix:4:3:
    attribute 'cardano_0_1_0' missing, at /home/clacke/git/fractalide/fractalide/release.nix:8:15